In [9]:
import json

# dataset = json.load(open('../data/datasets/conll04/conll04_test_clean.json'))
dataset = json.load(open('../data/datasets/scierc/scierc_test.json'))

rel_head_dict = {}
rel_tail_dict = {}

rels = set()
ents = set()

for data in dataset:
    for ent in data['entities']:
        ents.add(ent['type'])
    
    for rel in data['relations']:
        rels.add(rel['type'])

        if rel['type'] not in rel_head_dict:
            rel_head_dict[rel['type']] = {}
        if rel['type'] not in rel_tail_dict:
            rel_tail_dict[rel['type']] = {}
        
        head_ent_type = data['entities'][rel['head']]['type']
        tail_ent_type = data['entities'][rel['tail']]['type']

        rel_head_dict[rel['type']][head_ent_type] = rel_head_dict[rel['type']].get(head_ent_type, 0) + 1
        rel_tail_dict[rel['type']][tail_ent_type] = rel_tail_dict[rel['type']].get(tail_ent_type, 0) + 1
    
rels = sorted(rels)
ents = sorted(ents)

In [10]:
import numpy as np

rel_head_m = np.zeros((len(rels), len(ents)), dtype=np.float32)
rel_tail_m = np.zeros((len(rels), len(ents)), dtype=np.float32)

for rel_idx, rel_type in enumerate(rels):
    rel_head_sum = sum(rel_head_dict[rel_type].values())
    rel_tail_sum = sum(rel_tail_dict[rel_type].values())
    for ent_idx, ent_type in enumerate(ents):
        rel_head_m[rel_idx, ent_idx] = rel_head_dict[rel_type].get(ent_type, 0) / rel_head_sum
        rel_tail_m[rel_idx, ent_idx] = rel_tail_dict[rel_type].get(ent_type, 0) / rel_tail_sum

In [8]:
print(rels)
print(ents)
print(rel_head_m)
print(rel_tail_m)

['Kill', 'Live_In', 'Located_In', 'OrgBased_In', 'Work_For']
['Loc', 'Org', 'Other', 'Peop']
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [11]:
print(rels)
print(ents)
print(rel_head_m)
print(rel_tail_m)

['Compare', 'Conjunction', 'Evaluate-for', 'Feature-of', 'Hyponym-of', 'Part-of', 'Used-for']
['Generic', 'Material', 'Method', 'Metric', 'OtherScientificTerm', 'Task']
[[0.39473686 0.02631579 0.5263158  0.         0.05263158 0.        ]
 [0.0406504  0.06504065 0.24390244 0.04878049 0.41463414 0.18699187]
 [0.06593407 0.34065935 0.01098901 0.46153846 0.05494506 0.06593407]
 [0.         0.03389831 0.01694915 0.06779661 0.84745765 0.03389831]
 [0.05970149 0.20895523 0.35820895 0.05970149 0.20895523 0.10447761]
 [0.03174603 0.07936508 0.2857143  0.         0.44444445 0.15873016]
 [0.19699812 0.08442777 0.3846154  0.01313321 0.25891182 0.0619137 ]]
[[0.28947368 0.05263158 0.55263156 0.         0.10526316 0.        ]
 [0.02439024 0.08130081 0.24390244 0.04878049 0.40650406 0.19512194]
 [0.37362638 0.01098901 0.4065934  0.03296703 0.10989011 0.06593407]
 [0.08474576 0.18644068 0.18644068 0.08474576 0.3220339  0.13559322]
 [0.25373134 0.05970149 0.37313432 0.05970149 0.10447761 0.14925373]
 [